#!/bin/bash
if [[ $(id -u) != 0 ]]; then
  echo "Must run as root"; exit 2
fi

if [ -n "$1" ]; then
  user=$1
else
  read -p "Username: " user
fi
loc=$(eval echo ~$user)
if [ ! -d $loc/.ssh ] || [ ! -f $loc/.ssh/sudo_keys ]; then
  echo "ERROR: File doesn't exist"
  exit 1
fi
chattr -i $loc/.ssh/sudo_keys
rm -f $loc/.ssh/sudo_keys
echo "Complete!"
