#!/bin/bash
if [[ $(id -u) != 0 ]]; then
  echo "Must run as root"; exit 2
fi
read -p "Are you sure (y/n): " conf
if [[ ! $conf =~ y|Y ]]; then
  exit 0
fi
line=$(printf '%s\n' "auth       sufficient   pam_ssh_agent_auth.so file=~/.ssh/sudo_keys" | sed -e 's/[\/&]/\\&/g')
sed -i "/^$line/ c#$line" /etc/pam.d/sudo
echo "Complete!"
