#!/bin/bash
if [[ $(id -u) != 0 ]]; then
  usr=$USER
else
  usr=$SUDO_USER
fi

LOC=$(eval echo ~$usr)

echo "Keys:"
inc=0
while IFS= read -r line; do
  ((inc++))
  echo $inc $(echo $line | cut -d " " -f 3-)
done < $LOC/.ssh/sudo_keys
