#!/bin/bash
if [[ $(id -u) != 0 ]]; then
  echo "Must run as root"; exit 2
fi
line="auth       include      system-auth"
sed -i "/^$line/ c#$line" /etc/pam.d/sudo
line="password   include      system-auth"
sed -i "/^$line/ c#$line" /etc/pam.d/sudo
echo "Complete!"
