#!/bin/bash
if [[ $(id -u) != 0 ]]; then
  echo "Must run as root"; exit 2
fi

echo "Removing from user:" $SUDO_USER
LOC=$(eval echo ~$SUDO_USER)
src="$(dirname "$(realpath -s "$BASH_SOURCE")")"
if [ -n "$1" ]; then
  num=$1
else
  echo
  $src/ls
  echo
  read -p "Which: " num
fi
chattr -i $LOC/.ssh/sudo_keys
sed -i ${num}d $LOC/.ssh/sudo_keys
chattr +i $LOC/.ssh/sudo_keys
echo "Complete!"
