#!/bin/bash
if [[ $(id -u) != 0 ]]; then
  echo "Must run as root"; exit 2
fi

if [ -n "$1" ]; then
  user=$1
else
  read -p "Username: " user
fi
loc=$(eval echo ~$user)
src="$(dirname "$(realpath -s "$BASH_SOURCE")")"
if [ ! -d $loc/.ssh ] || [ ! -f $loc/.ssh/sudo_keys ]; then
  echo "ERROR: File doesn't exist"
  exit 1
fi
if [ ! -f $loc/.ssh/authorized_keys ]; then
  touch $loc/.ssh/authorized_keys
  chown $user:$user $loc/.ssh/authorized_keys
  chmod 644 $loc/.ssh/authorized_keys
fi
cat $loc/.ssh/sudo_keys >> $loc/.ssh/authorized_keys
$src/del
